//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rentalPropertyManagementApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApartmentLease
    {
        public int LeaseNumber { get; set; }
        public int ApartmentNumber { get; set; }
        public string ApartmentName { get; set; }
        public decimal MonthlyRent { get; set; }
        public int Months { get; set; }
        public string TenantId { get; set; }
    }
}
